### PR TITLE
Add support for percentages in `plot.euler()`

### LINKED ISSUE #48: add percentage to quantities
Hi,
First of all, thank you very much for this great package! 
I was wondering if it would be easy and/or useful to have the percentage printed as well as the numbers of elements in each set. 
Something maybe similar to the `print.mode = c("raw", "percent")` (from the VennDiagram package), to be added as parameter. 
So that the output would look like this:
Screenshot 2019-04-23 at 11 37 48

### PR DESCRIPTION
**Pull request by jolars**
This pull request resolves #48. The functionality mimics that of the other arguments `labels` and `quantities` in the call to `plot.euler()`. 

Here's an example:

```r
library(eulerr)

e <- euler(organisms)
plot(e, quantities = TRUE, percentages = TRUE)
```

image

### CODE REVIEW

**Comment by Cumol** [comment]
Works perfectly!

**Comment by Cumol** [comment]
Actually, I just noticed that the percentages are in relation to the data that is plotted in the euler, and not to the total data.

As an example:
```
  Cat1  Ca2 Cat3 Cat4 Cat5
1  FALSE FALSE  TRUE      TRUE   FALSE
2  FALSE FALSE FALSE      TRUE   FALSE
3  FALSE FALSE  TRUE     FALSE   FALSE
4  FALSE FALSE FALSE     FALSE   FALSE
5  FALSE FALSE FALSE      TRUE   FALSE
6   TRUE  TRUE  TRUE      TRUE   FALSE
```
Only data where it is "TRUE" is taken into account, but not those that are all "FALSE" /row 4 in this case.

Would it make send to include this information? For example, adapt the percentages to the total number and not only to the ones used to plot the euler?

**Comment by jolars** [comment]
You're right. It should definitely be in relation to the total, thanks.

**Comment by jolars** [comment]
Hrm, that shouldn't happen. I'll turn it into an issue and fix in the coming week.

**Comment by jolars** [comment]
@Cumol, regarding this:

> Only data where it is "TRUE" is taken into account, but not those that are all "FALSE" /row 4 in this case.
> 
> Would it make send to include this information? For example, adapt the percentages to the total number and not only to the ones used to plot the euler?

What exactly do you mean? The fourth row is essentially void in your example since that "observation" is not included in any of the sets, so I don't understand why it would count towards the total?

**Comment by maitra** [comment]
> This pull request resolves #48. The functionality mimics that of the other arguments `labels` and `quantities` in the call to `plot.euler()`.
> 
> Here's an example:
> 
> ```r
> library(eulerr)
> 
> e <- euler(organisms)
> plot(e, quantities = TRUE, percentages = TRUE)
> ```
> 
> image

I am unable to get the percentages in  the plot. 

Here is what I get:
```

library(eulerr)
e <- euler(organisms)
plot(e, quantities = TRUE, percentages = TRUE)

```

**Comment by jolars** [comment]
The API has changed @maitra. You now need:

``` r
library(eulerr)
e <- euler(organisms)
plot(e, quantities = list(type = c("counts", "percent")))
```



<sup>Created on 2022-03-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request merged**
